language: minimal

os: osx

before_install:
  - chmod +x bin/hugo

script:
  - cd exampleSite
  - ../bin/hugo --themesDir ../../ --theme hugomodo

# deploy removed as GitHub Releases creates source code zip and tar anyway
