language: minimal

os: osx

before_install:
  - chmod +x bin/hugo

stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      script:
        - cd exampleSite
        - ../bin/hugo --themesDir ../../ --theme hugomodo
    - stage: deploy
      script:
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - release_branch=$(echo ${TRAVIS_TAG} | cut -b 2-)
        - git checkout -b $release_branch
        - git push -u origin $release_branch
